name: "Danger JS"
on: [pull_request]

jobs:
  danger-js:
    name: Danger JS
    uses: kuzzleio/ci-tooling/.github/workflows/danger.yaml@master
    secrets: inherit
    with:
      DANGER_CONFIG: './.ci/danger.config.yml'